using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Options;
using Data.Entities;

namespace Business.Factories;

//Generated by ChatGPT-04-mini-high - Creates FirstName/LastName/ImageUri Claims for the logged-in User 
public class MemberClaimsPrincipalFactory(UserManager<MemberEntity> userManager, RoleManager<IdentityRole> roleManager, IOptions<IdentityOptions> optionsAccessor) : UserClaimsPrincipalFactory<MemberEntity, IdentityRole>(userManager, roleManager, optionsAccessor)
{
    protected override async Task<ClaimsIdentity> GenerateClaimsAsync(MemberEntity user)
    {
        var identity = await base.GenerateClaimsAsync(user);

        if (!string.IsNullOrWhiteSpace(user.FirstName))
        {
            identity.AddClaim(new Claim(ClaimTypes.GivenName, user.FirstName));
        }

        if (!string.IsNullOrWhiteSpace(user.LastName))
        {
            identity.AddClaim(new Claim(ClaimTypes.Surname, user.LastName));
        }

        if (!string.IsNullOrWhiteSpace(user.ImageUri))
        {
            identity.AddClaim(new Claim("ImageUri", user.ImageUri));
        }

        return identity;
    }
}