using Business.Interfaces;
using Domain.Models;

namespace Business.Models;

public abstract class ResponseResult : IResponseResult
{
    public bool Success { get; protected set; }
    public int StatusCode { get; protected set; }
    public string ErrorMessage { get; protected set; } = string.Empty;

    public static ResponseResult Ok()
    {
        return new SuccessResult(200);
    }

    public static ResponseResult BadRequest(string message)
    {
        return new ErrorResult(400, message);
    }

    public static ResponseResult NotFound(string message)
    {
        return new ErrorResult(404, message);
    }

    public static ResponseResult AlreadyExists(string message)
    {
        return new ErrorResult(409, message);
    }

    public static ResponseResult Error(string message)
    {
        return new ErrorResult(500, message);
    }
}

public class ResponseResult<T> : ResponseResult, IResponseResult<T>
{
    public T? Data { get; private set; }

    public static ResponseResult<T> Ok(T? data)
    {
        return new ResponseResult<T>
        {
            Success = true,
            StatusCode = 200,
            Data = data
        };
    }

    //Generated by ChatGPT 03-mini-high - It returns a type-safe error response. Used in catches for methods with return type Task<IResponseResult<IEnumerable<Models>>>
    public new static ResponseResult<T> Error(string message)
    {
        return new ResponseResult<T>
        {
            Success = false,
            StatusCode = 500,
            ErrorMessage = message,
        };
    }
}